parameters:
  test: true
  

jobs:
- job: Deploy123123
  steps:
  - task: DownloadPipelineArti123
    condition: eq( parameters.test  , true)
    displayName: Download artifact
    inputs:
      artifactName: 'Docs.BlogArchive.Comments.Artifact'
      path: '$(Build.ArtifactStagingDirectory)'

 
